import { PDFDocument, StandardFonts, rgb, PDFName, PDFArray, PDFString, PDFNumber, type PDFFont, type PDFPage } from "pdf-lib";
import type { GeneratedOutputs } from "@/utils/api";

// Brand palette (oklch-equivalent fallbacks in RGB 0-1)
const SAFFRON = rgb(1, 0.6, 0.2);
const TEAL = rgb(0.05, 0.58, 0.53);
const NAVY = rgb(0.12, 0.11, 0.29);
const INK = rgb(0.1, 0.1, 0.12);
const MUTED = rgb(0.42, 0.42, 0.48);
const LINE = rgb(0.88, 0.88, 0.92);
const CREAM = rgb(1, 0.97, 0.93);
const WHITE = rgb(1, 1, 1);

const PAGE_W = 595.28; // A4
const PAGE_H = 841.89;
const MARGIN_X = 48;
const MARGIN_TOP = 56;
const MARGIN_BOTTOM = 56;
const CONTENT_W = PAGE_W - MARGIN_X * 2;

interface Ctx {
  doc: PDFDocument;
  page: PDFPage;
  y: number;
  font: PDFFont;
  bold: PDFFont;
  italic: PDFFont;
  pageNumber: number;
  title: string;
}

function newPage(ctx: Ctx) {
  ctx.page = ctx.doc.addPage([PAGE_W, PAGE_H]);
  ctx.pageNumber += 1;
  ctx.y = PAGE_H - MARGIN_TOP;
  drawHeaderFooter(ctx);
}

function drawHeaderFooter(ctx: Ctx) {
  // Header bar
  ctx.page.drawRectangle({
    x: 0,
    y: PAGE_H - 28,
    width: PAGE_W,
    height: 28,
    color: NAVY,
  });
  ctx.page.drawText("HeadStart", {
    x: MARGIN_X,
    y: PAGE_H - 19,
    size: 11,
    font: ctx.bold,
    color: WHITE,
  });
  const title = ctx.title.length > 70 ? ctx.title.slice(0, 67) + "…" : ctx.title;
  const titleWidth = ctx.font.widthOfTextAtSize(title, 9);
  ctx.page.drawText(title, {
    x: PAGE_W - MARGIN_X - titleWidth,
    y: PAGE_H - 18,
    size: 9,
    font: ctx.font,
    color: WHITE,
  });

  // Footer
  ctx.page.drawLine({
    start: { x: MARGIN_X, y: 32 },
    end: { x: PAGE_W - MARGIN_X, y: 32 },
    thickness: 0.5,
    color: LINE,
  });
  ctx.page.drawText("Generated by HeadStart — India-first startup validation", {
    x: MARGIN_X,
    y: 18,
    size: 8,
    font: ctx.italic,
    color: MUTED,
  });
  const pageText = `Page ${ctx.pageNumber}`;
  const pw = ctx.font.widthOfTextAtSize(pageText, 8);
  ctx.page.drawText(pageText, {
    x: PAGE_W - MARGIN_X - pw,
    y: 18,
    size: 8,
    font: ctx.font,
    color: MUTED,
  });

  ctx.y = PAGE_H - MARGIN_TOP;
}

function ensureSpace(ctx: Ctx, needed: number) {
  if (ctx.y - needed < MARGIN_BOTTOM) newPage(ctx);
}

// Sanitize: WinAnsi encoding (used by Standard fonts) doesn't support many
// Unicode chars (₹, em-dashes, smart quotes, etc.). Replace gracefully.
function sanitize(text: string): string {
  if (!text) return "";
  return text
    .replace(/₹/g, "Rs ")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/\u2022/g, "*")
    .replace(/\u00A0/g, " ")
    // Strip anything still outside WinAnsi printable range
    .replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF]/g, "");
}

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const clean = sanitize(text);
  const paragraphs = clean.split("\n");
  const lines: string[] = [];
  for (const para of paragraphs) {
    const words = para.split(/\s+/);
    let line = "";
    for (const w of words) {
      const test = line ? line + " " + w : w;
      if (font.widthOfTextAtSize(test, size) > maxWidth && line) {
        lines.push(line);
        line = w;
      } else {
        line = test;
      }
    }
    if (line) lines.push(line);
    if (paragraphs.length > 1) lines.push("");
  }
  if (lines[lines.length - 1] === "") lines.pop();
  return lines;
}

function drawWrappedText(
  ctx: Ctx,
  text: string,
  opts: { size?: number; font?: PDFFont; color?: ReturnType<typeof rgb>; lineHeight?: number; x?: number; maxWidth?: number } = {}
): number {
  const size = opts.size ?? 10;
  const font = opts.font ?? ctx.font;
  const color = opts.color ?? INK;
  const lineHeight = opts.lineHeight ?? size * 1.4;
  const x = opts.x ?? MARGIN_X;
  const maxWidth = opts.maxWidth ?? CONTENT_W;
  const lines = wrapText(text, font, size, maxWidth);
  for (const line of lines) {
    ensureSpace(ctx, lineHeight);
    ctx.page.drawText(line, { x, y: ctx.y - size, size, font, color });
    ctx.y -= lineHeight;
  }
  return lines.length;
}

function drawSectionHeading(ctx: Ctx, label: string, accent = SAFFRON) {
  ensureSpace(ctx, 50);
  ctx.y -= 8;
  // Accent block
  ctx.page.drawRectangle({
    x: MARGIN_X,
    y: ctx.y - 22,
    width: 4,
    height: 22,
    color: accent,
  });
  ctx.page.drawText(sanitize(label), {
    x: MARGIN_X + 12,
    y: ctx.y - 18,
    size: 18,
    font: ctx.bold,
    color: NAVY,
  });
  ctx.y -= 30;
  // Underline
  ctx.page.drawLine({
    start: { x: MARGIN_X, y: ctx.y },
    end: { x: PAGE_W - MARGIN_X, y: ctx.y },
    thickness: 0.6,
    color: LINE,
  });
  ctx.y -= 14;
}

function drawSubheading(ctx: Ctx, label: string) {
  ensureSpace(ctx, 26);
  ctx.y -= 6;
  ctx.page.drawText(sanitize(label.toUpperCase()), {
    x: MARGIN_X,
    y: ctx.y - 10,
    size: 9,
    font: ctx.bold,
    color: TEAL,
  });
  ctx.y -= 18;
}

function drawStatCard(ctx: Ctx, x: number, y: number, w: number, h: number, label: string, value: string, accent: ReturnType<typeof rgb>) {
  ctx.page.drawRectangle({ x, y, width: w, height: h, color: WHITE, borderColor: LINE, borderWidth: 0.6 });
  ctx.page.drawRectangle({ x, y: y + h - 4, width: w, height: 4, color: accent });
  ctx.page.drawText(sanitize(label), { x: x + 12, y: y + h - 22, size: 8, font: ctx.bold, color: MUTED });
  ctx.page.drawText(sanitize(value), { x: x + 12, y: y + 14, size: 16, font: ctx.bold, color: NAVY });
}

function drawBadge(ctx: Ctx, x: number, y: number, text: string, color: ReturnType<typeof rgb>): number {
  const t = sanitize(text);
  const w = ctx.bold.widthOfTextAtSize(t, 8) + 12;
  const h = 14;
  ctx.page.drawRectangle({ x, y, width: w, height: h, color, borderWidth: 0 });
  ctx.page.drawText(t, { x: x + 6, y: y + 4, size: 8, font: ctx.bold, color: WHITE });
  return w;
}

function drawBulletList(ctx: Ctx, items: string[], opts: { bulletColor?: ReturnType<typeof rgb> } = {}) {
  const color = opts.bulletColor ?? TEAL;
  for (const item of items) {
    const lines = wrapText(item, ctx.font, 10, CONTENT_W - 18);
    ensureSpace(ctx, lines.length * 14);
    ctx.page.drawCircle({ x: MARGIN_X + 4, y: ctx.y - 6, size: 2, color });
    for (let i = 0; i < lines.length; i++) {
      ctx.page.drawText(lines[i], { x: MARGIN_X + 14, y: ctx.y - 10, size: 10, font: ctx.font, color: INK });
      ctx.y -= 14;
    }
    ctx.y -= 2;
  }
}

function drawSwatch(ctx: Ctx, x: number, y: number, w: number, h: number, hex: string, name: string) {
  const c = hexToRgb(hex);
  ctx.page.drawRectangle({ x, y: y + 22, width: w, height: h - 22, color: c });
  ctx.page.drawRectangle({ x, y, width: w, height: 22, color: WHITE, borderColor: LINE, borderWidth: 0.6 });
  ctx.page.drawText(sanitize(name), { x: x + 8, y: y + 12, size: 8, font: ctx.bold, color: NAVY });
  ctx.page.drawText(sanitize(hex), { x: x + 8, y: y + 3, size: 7, font: ctx.font, color: MUTED });
}

function hexToRgb(hex: string) {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const r = parseInt(full.slice(0, 2), 16) / 255 || 0;
  const g = parseInt(full.slice(2, 4), 16) / 255 || 0;
  const b = parseInt(full.slice(4, 6), 16) / 255 || 0;
  return rgb(r, g, b);
}

function addLinkAnnotation(ctx: Ctx, x: number, y: number, w: number, h: number, url: string) {
  const annot = ctx.doc.context.obj({
    Type: "Annot",
    Subtype: "Link",
    Rect: [x, y, x + w, y + h],
    Border: [0, 0, 0],
    A: { Type: "Action", S: "URI", URI: PDFString.of(url) },
  });
  const ref = ctx.doc.context.register(annot);
  let annots = ctx.page.node.lookup(PDFName.of("Annots"), PDFArray);
  if (!annots) {
    annots = ctx.doc.context.obj([]) as PDFArray;
    ctx.page.node.set(PDFName.of("Annots"), annots);
  }
  annots.push(ref);
  void PDFNumber;
}

function drawLink(ctx: Ctx, text: string, x: number, y: number, size: number, font: PDFFont, url: string, color = TEAL) {
  const t = sanitize(text);
  const w = font.widthOfTextAtSize(t, size);
  ctx.page.drawText(t, { x, y, size, font, color });
  ctx.page.drawLine({ start: { x, y: y - 1 }, end: { x: x + w, y: y - 1 }, thickness: 0.5, color });
  addLinkAnnotation(ctx, x, y - 2, w, size + 2, url);
  return w;
}

export async function buildReportPdf(report: GeneratedOutputs, ideaText: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const italic = await doc.embedFont(StandardFonts.HelveticaOblique);

  const ctx: Ctx = {
    doc,
    page: doc.addPage([PAGE_W, PAGE_H]),
    y: PAGE_H - MARGIN_TOP,
    font,
    bold,
    italic,
    pageNumber: 1,
    title: "Startup Validation Report",
  };
  drawHeaderFooter(ctx);

  // ---------- COVER ----------
  ctx.page.drawRectangle({ x: 0, y: PAGE_H - 240, width: PAGE_W, height: 200, color: CREAM });
  ctx.page.drawRectangle({ x: 0, y: PAGE_H - 244, width: PAGE_W, height: 4, color: SAFFRON });

  ctx.page.drawText("STARTUP VALIDATION REPORT", {
    x: MARGIN_X, y: PAGE_H - 80, size: 11, font: bold, color: TEAL,
  });
  ctx.page.drawText("HeadStart", {
    x: MARGIN_X, y: PAGE_H - 130, size: 36, font: bold, color: NAVY,
  });
  ctx.page.drawText("India-first startup validation", {
    x: MARGIN_X, y: PAGE_H - 158, size: 13, font: italic, color: MUTED,
  });
  const dateStr = new Date(report.generated_at).toLocaleString("en-IN", {
    dateStyle: "long", timeStyle: "short",
  });
  ctx.page.drawText(`Generated: ${dateStr}`, {
    x: MARGIN_X, y: PAGE_H - 200, size: 9, font, color: MUTED,
  });

  ctx.y = PAGE_H - 280;
  drawSubheading(ctx, "Founder's idea");
  drawWrappedText(ctx, ideaText, { size: 11, color: INK, lineHeight: 16 });
  ctx.y -= 8;

  // Quick at-a-glance market stats on cover
  ctx.y -= 6;
  drawSubheading(ctx, "Market opportunity at a glance");
  const cardW = (CONTENT_W - 16) / 3;
  const cardH = 56;
  ensureSpace(ctx, cardH + 4);
  drawStatCard(ctx, MARGIN_X, ctx.y - cardH, cardW, cardH, "TAM (Rs Cr)", report.market_data.tam.toLocaleString("en-IN"), SAFFRON);
  drawStatCard(ctx, MARGIN_X + cardW + 8, ctx.y - cardH, cardW, cardH, "SAM (Rs Cr)", report.market_data.sam.toLocaleString("en-IN"), TEAL);
  drawStatCard(ctx, MARGIN_X + (cardW + 8) * 2, ctx.y - cardH, cardW, cardH, "SOM Yr 1 (Rs Cr)", report.market_data.som.toLocaleString("en-IN"), NAVY);
  ctx.y -= cardH + 12;

  // ---------- 1. MARKET ----------
  newPage(ctx);
  drawSectionHeading(ctx, "1. Market Opportunity", SAFFRON);
  drawWrappedText(ctx,
    "Sized for the Indian market in Rupees Crore. TAM is the ceiling, SAM is what you can realistically reach with your model and language coverage, SOM is what you can win in Year 1.",
    { color: MUTED, size: 10 }
  );
  ctx.y -= 8;
  ensureSpace(ctx, cardH + 4);
  drawStatCard(ctx, MARGIN_X, ctx.y - cardH, cardW, cardH, "Total Addressable", "Rs " + report.market_data.tam.toLocaleString("en-IN") + " Cr", SAFFRON);
  drawStatCard(ctx, MARGIN_X + cardW + 8, ctx.y - cardH, cardW, cardH, "Serviceable", "Rs " + report.market_data.sam.toLocaleString("en-IN") + " Cr", TEAL);
  drawStatCard(ctx, MARGIN_X + (cardW + 8) * 2, ctx.y - cardH, cardW, cardH, "Obtainable Yr 1", "Rs " + report.market_data.som.toLocaleString("en-IN") + " Cr", NAVY);
  ctx.y -= cardH + 16;

  // ---------- 2. COMPETITORS ----------
  drawSectionHeading(ctx, "2. India-Specific Competitors", TEAL);
  for (const c of report.competitors) {
    ensureSpace(ctx, 80);
    const cardTop = ctx.y;
    const cardHc = 78;
    ctx.page.drawRectangle({
      x: MARGIN_X, y: cardTop - cardHc, width: CONTENT_W, height: cardHc,
      color: WHITE, borderColor: LINE, borderWidth: 0.6,
    });
    let nameW: number;
    if (c.url) {
      nameW = drawLink(ctx, c.name, MARGIN_X + 14, cardTop - 22, 13, bold, c.url, NAVY);
    } else {
      ctx.page.drawText(sanitize(c.name), {
        x: MARGIN_X + 14, y: cardTop - 22, size: 13, font: bold, color: NAVY,
      });
      nameW = bold.widthOfTextAtSize(sanitize(c.name), 13);
    }
    drawBadge(ctx, MARGIN_X + 14 + nameW + 10, cardTop - 22, c.type, c.type === "Unicorn" ? SAFFRON : TEAL);

    const rowY = cardTop - 42;
    const colW = (CONTENT_W - 28) / 4;
    const fields = [
      ["Funding", c.funding],
      ["Monthly users", c.monthly_users],
      ["Pricing", c.pricing],
    ];
    fields.forEach(([label, val], i) => {
      ctx.page.drawText(sanitize(label), { x: MARGIN_X + 14 + colW * i, y: rowY, size: 7, font: bold, color: MUTED });
      ctx.page.drawText(sanitize(val), { x: MARGIN_X + 14 + colW * i, y: rowY - 11, size: 9, font, color: INK });
    });
    ctx.page.drawText("Their weakness", { x: MARGIN_X + 14, y: cardTop - 60, size: 7, font: bold, color: MUTED });
    const wkLines = wrapText(c.weakness, italic, 9, CONTENT_W - 28);
    ctx.page.drawText(wkLines[0] ?? "", { x: MARGIN_X + 14, y: cardTop - 71, size: 9, font: italic, color: INK });

    ctx.y = cardTop - cardHc - 8;
  }

  // ---------- 3. PRODUCT ----------
  newPage(ctx);
  drawSectionHeading(ctx, "3. Product Blueprint", NAVY);
  drawSubheading(ctx, "MVP features (priority + effort)");
  for (const f of report.product.mvp_features) {
    ensureSpace(ctx, 22);
    const cardTop = ctx.y;
    ctx.page.drawRectangle({
      x: MARGIN_X, y: cardTop - 20, width: CONTENT_W, height: 20,
      color: WHITE, borderColor: LINE, borderWidth: 0.5,
    });
    ctx.page.drawText(sanitize(f.name), { x: MARGIN_X + 10, y: cardTop - 14, size: 10, font, color: INK });
    const badgeColor = f.priority === "Must" ? SAFFRON : f.priority === "Should" ? TEAL : MUTED;
    const bx = PAGE_W - MARGIN_X - 110;
    drawBadge(ctx, bx, cardTop - 17, f.priority, badgeColor);
    ctx.page.drawText(sanitize(f.effort), { x: PAGE_W - MARGIN_X - 60, y: cardTop - 14, size: 9, font: italic, color: MUTED });
    ctx.y = cardTop - 24;
  }

  ctx.y -= 6;
  drawSubheading(ctx, "User flow");
  for (let i = 0; i < report.product.user_flow.length; i++) {
    const step = report.product.user_flow[i];
    ensureSpace(ctx, 26);
    ctx.page.drawCircle({ x: MARGIN_X + 10, y: ctx.y - 9, size: 9, color: TEAL });
    ctx.page.drawText(String(i + 1), { x: MARGIN_X + (i + 1 < 10 ? 7 : 4), y: ctx.y - 12, size: 9, font: bold, color: WHITE });
    const lines = wrapText(step, font, 10, CONTENT_W - 32);
    for (let j = 0; j < lines.length; j++) {
      ctx.page.drawText(lines[j], { x: MARGIN_X + 28, y: ctx.y - 12 - j * 13, size: 10, font, color: INK });
    }
    ctx.y -= Math.max(22, lines.length * 13 + 6);
  }

  ctx.y -= 6;
  drawSubheading(ctx, "Recommended Swadeshi stack");
  for (const s of report.swadeshi_stack) {
    ensureSpace(ctx, 50);
    const cardTop = ctx.y;
    ctx.page.drawRectangle({
      x: MARGIN_X, y: cardTop - 48, width: CONTENT_W, height: 48,
      color: WHITE, borderColor: LINE, borderWidth: 0.5,
    });
    ctx.page.drawRectangle({ x: MARGIN_X, y: cardTop - 48, width: 3, height: 48, color: TEAL });
    if (s.url) {
      drawLink(ctx, s.name, MARGIN_X + 12, cardTop - 14, 11, bold, s.url, NAVY);
    } else {
      ctx.page.drawText(sanitize(s.name), { x: MARGIN_X + 12, y: cardTop - 14, size: 11, font: bold, color: NAVY });
    }
    ctx.page.drawText(sanitize(`${s.category} • ${s.price}`), { x: MARGIN_X + 12, y: cardTop - 26, size: 8, font, color: MUTED });
    const whyLines = wrapText(s.why, font, 9, CONTENT_W - 24);
    ctx.page.drawText(whyLines[0] ?? "", { x: MARGIN_X + 12, y: cardTop - 39, size: 9, font, color: INK });
    ctx.y = cardTop - 54;
  }

  // ---------- 4. BRAND ----------
  newPage(ctx);
  drawSectionHeading(ctx, "4. Brand Kit", SAFFRON);
  drawSubheading(ctx, "Name suggestions");
  for (const n of report.brand.names) {
    ensureSpace(ctx, 36);
    ctx.page.drawText(sanitize(n.name), { x: MARGIN_X, y: ctx.y - 12, size: 13, font: bold, color: SAFFRON });
    ctx.y -= 16;
    drawWrappedText(ctx, n.rationale, { size: 9, color: MUTED, lineHeight: 12 });
    ctx.y -= 4;
  }

  drawSubheading(ctx, "Taglines");
  for (const t of report.brand.taglines) {
    ensureSpace(ctx, 18);
    drawWrappedText(ctx, `"${t}"`, { size: 11, font: italic, color: INK });
    ctx.y -= 2;
  }

  drawSubheading(ctx, "Brand voice");
  drawWrappedText(ctx, report.brand.tone, { size: 10, color: INK });

  drawSubheading(ctx, "Color palette");
  ensureSpace(ctx, 80);
  const swW = (CONTENT_W - 24) / 4;
  const swH = 70;
  for (let i = 0; i < report.brand.palette.length; i++) {
    const p = report.brand.palette[i];
    drawSwatch(ctx, MARGIN_X + (swW + 8) * i, ctx.y - swH, swW, swH, p.hex, p.name);
  }
  ctx.y -= swH + 12;

  drawSubheading(ctx, "Logo prompt (paste into any image generator)");
  ctx.page.drawRectangle({
    x: MARGIN_X, y: ctx.y - getPromptBoxHeight(ctx, report.brand.logo_prompt),
    width: CONTENT_W, height: getPromptBoxHeight(ctx, report.brand.logo_prompt),
    color: CREAM, borderColor: SAFFRON, borderWidth: 0.6,
  });
  const promptLines = wrapText(report.brand.logo_prompt, font, 9, CONTENT_W - 20);
  let py = ctx.y - 14;
  for (const line of promptLines) {
    if (py < MARGIN_BOTTOM + 10) {
      ctx.y = py - 4;
      newPage(ctx);
      py = ctx.y - 14;
    }
    ctx.page.drawText(line, { x: MARGIN_X + 10, y: py, size: 9, font, color: INK });
    py -= 12;
  }
  ctx.y = py - 8;

  // ---------- 5. DATA ----------
  newPage(ctx);
  drawSectionHeading(ctx, "5. Data & Unit Economics", TEAL);

  drawSubheading(ctx, "Key metrics");
  const kpiW = (CONTENT_W - 24) / 4;
  const kpiH = 56;
  ensureSpace(ctx, kpiH + 4);
  for (let i = 0; i < report.data.kpis.length; i++) {
    const k = report.data.kpis[i];
    drawStatCard(ctx, MARGIN_X + (kpiW + 8) * i, ctx.y - kpiH, kpiW, kpiH, k.label, k.value, [SAFFRON, TEAL, NAVY, SAFFRON][i % 4]);
  }
  ctx.y -= kpiH + 16;

  drawSubheading(ctx, "Unit economics");
  ensureSpace(ctx, 40);
  ctx.page.drawText(`LTV: Rs ${report.data.unit_economics.ltv.toLocaleString("en-IN")}`, { x: MARGIN_X, y: ctx.y - 12, size: 11, font: bold, color: TEAL });
  ctx.page.drawText(`CAC: Rs ${report.data.unit_economics.cac.toLocaleString("en-IN")}`, { x: MARGIN_X + 180, y: ctx.y - 12, size: 11, font: bold, color: SAFFRON });
  ctx.page.drawText(`Payback: ${report.data.unit_economics.payback_months} months`, { x: MARGIN_X + 360, y: ctx.y - 12, size: 11, font: bold, color: NAVY });
  ctx.y -= 24;

  drawSubheading(ctx, "Conversion funnel");
  const widths = [1, 0.7, 0.45, 0.28];
  for (let i = 0; i < report.data.funnel.length; i++) {
    const f = report.data.funnel[i];
    ensureSpace(ctx, 26);
    ctx.page.drawText(sanitize(f.stage), { x: MARGIN_X, y: ctx.y - 10, size: 9, font, color: INK });
    const rateW = bold.widthOfTextAtSize(sanitize(f.rate), 9);
    ctx.page.drawText(sanitize(f.rate), { x: PAGE_W - MARGIN_X - rateW, y: ctx.y - 10, size: 9, font: bold, color: TEAL });
    ctx.y -= 14;
    const barBg = CONTENT_W;
    ctx.page.drawRectangle({ x: MARGIN_X, y: ctx.y - 6, width: barBg, height: 6, color: rgb(0.93, 0.94, 0.96) });
    ctx.page.drawRectangle({ x: MARGIN_X, y: ctx.y - 6, width: barBg * (widths[i] ?? 0.2), height: 6, color: TEAL });
    ctx.y -= 14;
  }

  // ---------- 6. CONTENT ----------
  newPage(ctx);
  drawSectionHeading(ctx, "6. Launch Content Pack", NAVY);

  drawSubheading(ctx, "Landing page hero");
  ensureSpace(ctx, 80);
  const heroH = 72;
  ctx.page.drawRectangle({ x: MARGIN_X, y: ctx.y - heroH, width: CONTENT_W, height: heroH, color: CREAM, borderColor: LINE, borderWidth: 0.6 });
  ctx.page.drawText(sanitize(report.content.landing_headline), { x: MARGIN_X + 14, y: ctx.y - 26, size: 14, font: bold, color: NAVY });
  const subLines = wrapText(report.content.landing_sub, font, 10, CONTENT_W - 28);
  for (let i = 0; i < Math.min(subLines.length, 2); i++) {
    ctx.page.drawText(subLines[i], { x: MARGIN_X + 14, y: ctx.y - 46 - i * 13, size: 10, font, color: MUTED });
  }
  ctx.y -= heroH + 12;

  drawSubheading(ctx, "Social posts");
  for (const p of report.content.social_posts) {
    const lines = wrapText(p.copy, font, 10, CONTENT_W - 24);
    const cardHc = 24 + lines.length * 13 + 12;
    ensureSpace(ctx, cardHc + 6);
    const cardTop = ctx.y;
    ctx.page.drawRectangle({ x: MARGIN_X, y: cardTop - cardHc, width: CONTENT_W, height: cardHc, color: WHITE, borderColor: LINE, borderWidth: 0.5 });
    drawBadge(ctx, MARGIN_X + 12, cardTop - 18, p.platform, TEAL);
    for (let i = 0; i < lines.length; i++) {
      ctx.page.drawText(lines[i], { x: MARGIN_X + 12, y: cardTop - 32 - i * 13, size: 10, font, color: INK });
    }
    ctx.y = cardTop - cardHc - 6;
  }

  ctx.y -= 4;
  drawSubheading(ctx, "Cold email template");
  ensureSpace(ctx, 24);
  ctx.page.drawText("Subject:", { x: MARGIN_X, y: ctx.y - 10, size: 9, font: bold, color: MUTED });
  ctx.page.drawText(sanitize(report.content.cold_email.subject), { x: MARGIN_X + 50, y: ctx.y - 10, size: 10, font: bold, color: INK });
  ctx.y -= 18;
  drawWrappedText(ctx, report.content.cold_email.body, { size: 10, color: INK, lineHeight: 14 });

  return await doc.save();
}

function getPromptBoxHeight(ctx: Ctx, text: string): number {
  const lines = wrapText(text, ctx.font, 9, CONTENT_W - 20);
  // capped to remaining page; the renderer handles spillover
  return Math.min(lines.length * 12 + 24, ctx.y - MARGIN_BOTTOM);
}
